### ISSUE TITLE
Theme not advertising atom feed

### ISSUE THREAD

**Issue by demure** [ingwinlu/pelican-twitchy#13]
It appears that there is no ATOM/RSS link built into this theme.
Perhaps and item should be added to the side bar for this?

**Comment by ingwinlu** [comment]
https://github.com/ingwinlu/pelican-twitchy/blob/master/templates/base.html#L72

**Comment by demure** [comment]
I guess I don't understand where it should be appearing, as your [site](https://www.heroicdebugging.biz/) has an [atom feed](https://www.heroicdebugging.biz/feeds/all.atom.xml), but I don't see in in your sidebar or anywhere else on the page.

**Comment by ingwinlu** [comment]
it would not appear for a normal 'browser', it is just metadata. if your browser has something similar like  https://chrome.google.com/webstore/detail/rss-feed-reader/pnjaodmkngahhkoihejjehlcdlnohgmp however it would pick it up and offer to 'follow' the feed.

There is no explicit link shown in the page. If you want one you would need to change the templates. 

As long as it looks ok and does not overload the theme (only very little people use rss/atom readers) I would accept PR's adding such a feature.

**Comment by fuzzmz** [comment]
@demure, just add it under the social widget in the pelican config file and it'll show up just fine.

For example my config looks like:

```python
SOCIAL = (
            ('Twitter', 'https://twitter.com/fuzzmz'),
            ('GitHub', 'https://github.com/fuzzmz'),
            ('Google+', 'https://plus.google.com/+serbanconstantin'),
            # ('RSS', SITEURL + '/' + FEED_ALL_ATOM),
            ('RSS', 'https://feeds.feedburner.com/fuzzmeuk'),
          )
```

This translates into 
![social](https://cloud.githubusercontent.com/assets/1335181/14431594/04c85dde-000f-11e6-9732-b7f95c738404.PNG)

**Comment by demure** [comment]
Thanks, I should have thought of that.
A lot better than the three way redirect page I was using https://notabug.org/demure/demu.red/src/master/content/pages/ATOM.md
